### PR TITLE
[Feature] Mobile Support

### PR DESCRIPTION
**Pull request by Eroxl**
# Description
Add proper styling for components and the page on mobile

# Screenshots
## Before
<div>
  
  
</div>

## After
<div>

</div>

### CODE REVIEW

**Comment by tobycm** [comment]
image
change these and I will merge

**Comment by Eroxl** [comment]
@tobycm 
It's a NextJS thing you can't select by element... this is why I use tailwind

**Comment by tobycm** [comment]
> @tobycm It's a NextJS thing you can't select by element... this is why I use tailwind

I mean put the <> on the same line pls, I like the `{styles.nav}`

**Review by tobycm — APPROVED** [review]
nice work man, thanks for fixing the hanging `>` on single-attribute elements

**Pull request merged**
